all: 6gon-final gen-6gon-cube

6gon-final: 6gon-final.c
	gcc 6gon-final.c -std=c99 -O2 -o 6gon-final

gen-6gon-cube: gen-6gon-cube.c
	gcc gen-6gon-cube.c -std=c99 -O2 -o gen-6gon-cube

clean:
	rm 6gon-final gen-6gon-cube
